esphome:
  name: shinwabms
  includes:
    - shinwabms.h

esp8266:
  board: esp12e

logger:
  level: DEBUG

web_server:
  port: 80

api:
  password: ""

ota:
  password: ""

wifi:
  networks:
  - ssid: "Network"
    password: "Password"

  ap:
    ssid: "Shinwabms Fallback Hotspot"
    password: "Pa$sword"

captive_portal:

uart:
  id: uart_bus
  tx_pin: GPIO12
  rx_pin: GPIO13
  baud_rate: 9600

sensor:
- platform: custom
  lambda: |-
    auto ShinwaBMS = new ShinwaBMSuartComponent(id(uart_bus));
    App.register_component(ShinwaBMS);
    return {
        ShinwaBMS->batteryVoltage,
        ShinwaBMS->batteryCurrent,
        ShinwaBMS->tempSensorMax,
        ShinwaBMS->tempSensorAvg,
        ShinwaBMS->tempSensorMin,
        ShinwaBMS->batteryCellMax,
        ShinwaBMS->batteryCellMin,
        ShinwaBMS->batteryCellAvg,
        ShinwaBMS->batteryCapacity
    };

  sensors:
  - name: "Battery voltage"
    unit_of_measurement: V
    accuracy_decimals: 3
    device_class: "voltage"

  - name: "Battery current"
    unit_of_measurement: A
    accuracy_decimals: 2
    device_class: "current"

  - name: "Battery temperature Hi"
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: "temperature"

  - name: "Battery temperature Avg"
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: "temperature"

  - name: "Battery temperature Lo"
    unit_of_measurement: °C
    accuracy_decimals: 1
    device_class: "temperature"

  - name: "Battery cell voltage Hi"
    unit_of_measurement: V
    accuracy_decimals: 3
    device_class: "voltage"

  - name: "Battery cell voltage Lo"
    unit_of_measurement: V
    accuracy_decimals: 3
    device_class: "voltage"

  - name: "Battery cell voltage Avg"
    unit_of_measurement: V
    accuracy_decimals: 3
    device_class: "voltage"

  - name: "Battery capacity"
    unit_of_measurement: Ah
    accuracy_decimals: 1
    device_class: "battery"


#- platform: adc
#  pin: VCC
#  name: "VCC Voltage"

#- platform: wifi_signal
#  name: "WiFi Signal"
#  update_interval: 60s